### ISSUE TITLE
22级数据院专硕新生请教

### ISSUE THREAD

**Issue by ghost** [corilei/jc-python-guide#1]
作者您好，
        我是华东师大数据院22级专硕新生，请问方便加您联系方式请教问题吗？🤣😋

**Comment by leicheng42** [comment]
微信号&nbsp; corilei



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [corilei/jc-python-guide] 22级数据院专硕新生请教 (Issue #1)





 
作者您好，
 我是华东师大数据院22级专硕新生，请问方便加您联系方式请教问题吗？🤣😋
